#
# This dockerfile is used for dev with docker-compose
#

ARG BASE_VERSION=latest

FROM olel/rv1106-buildroot-base:$BASE_VERSION AS local

WORKDIR /root/buildroot

CMD ["python3", "-m", "http.server", "8088"]